false_pos <- c(
    "ELEVENTH" = "SEVENTH",
    "\\bRAINS\\b" = "HAINS",
    "\\bMORT Sb" = "NORTH S",
    "SPARP" = "SHARK",
    "NORMAN" = "GORMAN",
    "DARWIN" = "IRWIN",
    "\\bREID\\b" = "\\bENID\\b",
    "BARCROFT" = "BANCROFT",
    "LOLLARD" = "COLLARD",
    "CALLIDE S" = "LAKE CALLIDE",
    "VIEWPOINT" = "\\bVIEW\\b",
    "\\bWOOD\\b" = "PINKWOOD",
    "MANNING" = "\\bANNE\\b",
    "\\bWEST\\b" = "WESTERN",
    "VICTORIA" = "\\bVICTOR\\b",
    "(?<!BACK )BEACH" = "BACK BEACH",
    "STEPHENSON" = "STEPHEN\\b",
    "CROMARTY ROAD" = "CROMARTY SID",
    "JOSEPHFINA\\b" = "JOSEPHINE",
    "LEAHY\\b" = "LEAHYS",
    "\\bMAY S\\b" = "\\bMARY S\\B",
    "\\bBURNLEY\\b" = "\\bBURLEY\\b",
    "\\bMAY\\b" = "MAYFAIR\\b",
    "\\bEVAN\\b" = "\\bEVANS\\b",
    "NEWHAM\\b" = "HAM\\b",
    "HERBERTON" = "HERBERT\\b"
)

